# Generated by Django 5.1.4 on 2024-12-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterFarmingApp', '0004_testimonial_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
    ]
