# Generated by Django 5.1.4 on 2024-12-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterFarmingApp', '0005_remove_testimonial_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
