# Generated by Django 5.1.4 on 2024-12-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterFarmingApp', '0007_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='reviewer',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
