# Generated by Django 5.1.4 on 2024-12-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterFarmingApp', '0008_testimonial_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='Profile_image',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='reviewerid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(blank=True, default='./static/img/noProfile.png', null=True, upload_to='profile_image/'),
        ),
    ]
