# Generated by Django 5.1.4 on 2024-12-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterFarmingApp', '0009_remove_testimonial_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
