# Generated by Django 5.1.4 on 2024-12-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterFarmingApp', '0011_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
