# Generated by Django 5.1.4 on 2024-12-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betterFarmingApp', '0012_alter_testimonial_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
